[zsh]
update = 'always'
"~/.zshrc" = 'zsh/zshrc'
"~/.config/zsh/config.d/main.zsh" = 'zsh/main.zsh'
"~/.config/zsh/config.d/prompt.zsh" = 'zsh/prompt.zsh'
"~/.config/zsh/config.d/export.zsh" = 'zsh/export.zsh'
"~/.config/zsh/config.d/alias.zsh" = 'zsh/alias.zsh'
"~/.config/zsh/config.d/tool/main.zsh" = 'zsh/tool/main.zsh'
"~/.config/zsh/config.d/tool/autojump.zsh" = 'zsh/tool/autojump.zsh'
"~/.config/zsh/config.d/tool/flutter.zsh" = 'zsh/tool/flutter.zsh'
"~/.config/zsh/config.d/tool/asdf.zsh" = 'zsh/tool/asdf.zsh'
"~/.config/zsh/config.d/tool/bun.zsh" = 'zsh/tool/bun.zsh'
"~/.config/zsh/config.d/function/main.zsh" = 'zsh/function/main.zsh'
"~/.config/zsh/config.d/function/git.zsh" = 'zsh/function/git.zsh'
"~/.config/zsh/config.d/function/sh.zsh" = 'zsh/function/sh.zsh'
"~/.config/zsh/config.d/function/w2x.zsh" = 'zsh/function/w2x.zsh'

[zsh-Decim]
update = ['Decim']
"~/.config/zsh/config.d/path.zsh" = 'zsh/Decim/path.zsh'
"~/.config/zsh/config.d/conda.zsh" = 'zsh/Decim/conda.zsh'

[zsh-Nona]
update = ['Nona']
"~/.config/zsh/config.d/path.zsh" = 'zsh/Nona/path.zsh'
"~/.config/zsh/config.d/conda.zsh" = 'zsh/Nona/conda.zsh'

[vscode]
update = 'always'
"~/.config/Code/User/settings.json" = 'vscode/settings.json'

[grub]
update = 'optional'
"/etc/default/grub" = 'grub/grub'
"/etc/default/grub_bg.png" = 'grub/grub_bg_640x480_stretched_dark.png'

[kitty]
update = 'always'
"~/.config/kitty/kitty.conf" = 'kitty/kitty.conf'
"~/.config/kitty/Argonaut.conf" = 'kitty/Argonaut.conf'

[neofetch]
update = 'optional'
"~/.config/neofetch/config.conf" = 'neofetch/config.conf'
"~/.config/neofetch/img.png" = 'neofetch/img.png'

[yapf]
update = 'always'
"~/.config/yapf/style" = 'yapf'

[font]
update = 'never'
"~/.local/share/fonts/*" = 'font/*'

[DE]
update = 'never'
"~/.icons/*" = 'DE/cursor/*'
"~/.themes/*" = 'DE/theme/*'
"/usr/share/icons/*" = 'DE/icon/*'
"/usr/share/mint-artwork/sounds/*" = 'DE/sound/*'
