[zsh]
update = [ 'Decim' ]
"~/.zshrc" = 'zsh/zshrc'
"~/.config/zsh/config.d/main.zsh" = 'zsh/main.zsh'
"~/.config/zsh/config.d/alias.zsh" = 'zsh/alias.zsh'
"~/.config/zsh/config.d/function.zsh" = 'zsh/function.zsh'
"~/.config/zsh/config.d/export.zsh" = 'zsh/export.zsh'
"~/.config/zsh/config.d/conda.zsh" = 'zsh/conda.zsh'

[vscode]
update = [ 'Decim' ]
"~/.config/Code/User/settings.json" = 'vscode/settings.json'

[grub]
update = 'optional'
"/etc/default/grub" = 'grub/grub'
"/etc/default/grub_bg.png" = 'grub/grub_bg_640x480_stretched_dark.png'

[kitty]
update = 'always'
"~/.config/kitty/kitty.conf" = 'kitty/kitty.conf'
"~/.config/kitty/Argonaut.conf" = 'kitty/Argonaut.conf'

[neofetch]
update = 'optional'
"~/.config/neofetch/config.conf" = 'neofetch/config.conf'
"~/.config/neofetch/img.conf" = 'neofetch/img.png'

[yapf]
update = 'always'
"~/.config/yapf/style" = 'yapf'

[font]
update = 'never'
"~/.local/share/fonts/*" = 'font/*'

[DE]
update = 'never'
"~/.icons/*" = 'DE/cursor/*'
"~/.themes/*" = 'DE/theme/*'
"/usr/share/icons/*" = 'DE/icon/*'
"/usr/share/mint-artwork/sounds/*" = 'DE/sound/*'
